config/routes.rb
Rails.application.routes.draw do
  resources  :cats, only:[:index, :show, :new, :edit, :update, :create]
  root to: 'cats#index'
  resources :cat_rental_requests, only:[:new,:create]
  post "/cat_rental_requests/:id/approve", to: "cat_rental_requests#approve!", as: "approve"
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :sex, inclusion: { in: ["M", "F"] }
  validates :name, :color, :sex, :description, :birth_date, presence: true

  has_many :requests,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion:{in: ["Approved","Pending","Denied"]}
  validate :overlapping_approved_requests
  validate :valid_dates
  belongs_to :cat

  def approve!
    unless self.status == "Denied"
      self.transaction do
        self.status = "Approved"
        self.save
        self.overlapping_requests.map do |request|
          request.status = "Denied"
          request.save
        end
      end
      return true
    else
      return false
    end
  end

  def deny!
    self.transaction do
      self.status = "Denied"
      self.save
    end
  end

  def overlapping_requests
    output = []
    pending_cat = Cat.find(self.cat_id)
    all_requests = pending_cat.requests
    all_requests.each do |request|
      beginning_date = request.start_date
      finishing_date = request.end_date
      truth_array = []
      truth_array << self.start_date.between?(beginning_date,finishing_date)
      truth_array << self.end_date.between?(beginning_date,finishing_date)
      truth_array << beginning_date.between?(self.start_date,self.end_date)
      truth_array << finishing_date.between?(self.start_date,self.end_date)
      if truth_array.any?{|x| x}
        output << request unless request == self
      end
    end
    output
  end

  def overlapping_approved_requests
    if overlapping_requests.any? { |request| request.status == "Approved" } &&
      self.status == "Approved"
      self.errors[:overlapping_request] << "Overlaps with existing request"
    end
  end

  def valid_dates
    if self.start_date > self.end_date
      self.errors[:date_error] << "Start date must be before end date"
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
  end

  def create
    a = CatRentalRequest.new(rental_params)
    if a.save
      render json: a
    else
      render json: a.errors.full_messages
    end
  end

  def approve!
    if CatRentalRequest.find(params[:id]).approve!
      redirect_to :back
    else
      render text: "Something went wrong"
    end
  end

  private
  def rental_params
    params.require(:ncr_request).permit!
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
    
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)
    redirect_to cat_url(@cat)
  end

  def create
    cat = Cat.new(cat_params)

    if cat.save
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages
    end
  end

  private

  def cat_params
    params.require(:cats).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Cat Rental Request</title>
  </head>
  <body>
    <h1>Make a Request</h1>
    <form class="request_form" action="/cat_rental_requests/" method="post">
      <label>Cat Name
        <select class="cat" name="ncr_request[cat_id]">
          <% @cats.each do |cat| %>
            <option value="<%= cat.id %>"><%= cat.name %></option>
          <% end %>
        </select>
      </label>
      <label>Start Date
        <input type="date" name="ncr_request[start_date]">
      </label>
      <label>End Date
        <input type="date" name="ncr_request[end_date]">
      </label>
      <input type="submit" value="Submit Request">
    </form>
  </body>
</html>

app/views/cats/_form.html.erb
<% if @cat.persisted? %>
  <% action = "/cats/#{@cat.id}" %>
  <% name = "_method" %>
<% else %>
  <% action = "/cats" %>
  <% name = "bumblebee" %>
<% end %>


<form class="new_cat" action=<%= action %> method="post">
  <input type="hidden" name=<%= name %> value="patch">
  <label> Name
    <input type ="text" name = "cats[name]" value="<%= @cat.name %>">
  </label>



  <label>Sex
    <label>F
      <input type="radio" name="cats[sex]" value="F" <%= "checked" if @cat.sex == "F" %>>
    </label>
    <label>M
    <input type="radio" name="cats[sex]" value="M" <%= "checked" if @cat.sex == "M" %>>
    </label>
  </label>


  <label> Birth Date
    <input type="Date" name="cats[birth_date"] value = "<%= @cat.birth_date.to_s %>" >
  </label>

  <label> Color
    <select name = "cats[color]" default="">
      <option value="blue" <%= "selected" if @cat.color == "blue" %>>blue</option>
      <option value="fuschia" <%= "selected" if @cat.color == "fuschia" %>>fuschia</option>
      <option value="yellow" <%= "selected" if @cat.color == "yellow" %> >yellow</option>
      <option value="chartreus" <%= "selected" if @cat.color == "chartreus" %>>chartreus</option>
      <option value="red" <%= "selected" if @cat.color == "red" %>>red</option>
      <option value="turqoise" <%= "selected" if @cat.color == "turqoise" %>>turqoise</option>
      <option value="puce" <%= "selected" if @cat.color == "puce" %>>puce</option>
    </select>
  </label>

  <label>Description
    <textarea name="cats[description]" rows="10" cols="40" placeholder="Describe the Kitty"> <%= @cat.description %></textarea>
  </label>

  <input type="submit" value="Save">
</form>

app/views/cats/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Cat Page</title>
  </head>
  <body>
    <%= render "form" %>
  </body>
</html>

app/views/cats/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>99 Cats</title>
  </head>
  <body>
    <h1>Welcome to 99 Cats</h1>
    <table border="1">
      <tr>
        <th>
          Name
        </th>
        <th>
          Link
        </th>
      </tr>
      <% @cats.each do |cat| %>
        <tr>
          <td>
            <%= cat.name %>
          </td>
          <td>
            <%= link_to "Cat Page",cat_path(cat)%>
          </td>
        </tr>
        <% end %>
    </table>
    <ul>
      <li> <%= link_to("Create a new cat",new_cat_url) %> </li>
      <li> <%= link_to("Submit a cat rental request", new_cat_rental_request_url) %> </li>
    </ul>

  </body>
</html>

app/views/cats/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Cat Page</title>
  </head>
  <body>
    <%= render "form" %>
  </body>
</html>

<!-- <form class="new_cat" action="/cats" method="post">
  <label> Name
    <input type ="text" name = "cats[name]" placeholder="Kittys Name">
  </label>



  <label>Sex
    <label>F
      <input type="radio" name="cats[sex]" value="F">
    </label>
    <label>M
    <input type="radio" name="cats[sex]" value="M">
    </label>
  </label>


  <label> Birth Date
    <input type="Date" name="cats[birth_date"]>
  </label>

  <label> Color
    <select name = "cats[color]" default="">
      <option selected disabled>Pick a Color</option>
      <option value="blue">blue</option>
      <option value="fuschia">fuschia</option>
      <option value="yellow">yellow</option>
      <option value="chartreus">chartreus</option>
      <option value="red">red</option>
      <option value="turqoise">turqoise</option>
      <option value="puce">puce</option>
    </select>
  </label>

  <label>Description
    <textarea name="cats[description]" rows="10" cols="40" placeholder="Describe the Kitty"></textarea>
  </label>
</form> -->

app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Here is the Kitty Info</title>
  </head>
  <body>
    <h1><%= @cat.name %></h1>
    <% catimg_link = "http://placekitten.com/200/#{300+@cat.id}" %>
    <img src="<%= catimg_link %>" alt="Cute Kitty" />
    <p> <%= @cat.description %> </p>

    <h2> Requests </h2>
    <table border=1>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Approve?</th>
      </tr>
      <% @cat.requests.sort{|request| request.start_date}.each do |request| %>
        <tr>
          <td> <%= request.start_date.to_s %> </td>
          <td> <%= request.end_date.to_s %> </td>
          <td> <%= request.status%> </td>
          <form action= "<%= approve_path(request) %>" method="post">
          <td><input type="<%= request.status == "Pending" ? "submit" : "hidden" %>" name="name" value="Approve!"></td>
          </form>
        </tr>
      <% end %>
    </table>

    <ul>
      <li> <%= link_to("Make New Request",new_cat_rental_request_url) %> </li>
      <li> <%= link_to("Back to Main Page", cats_url) %> </li>
      <li> <%= link_to("Edit Cat", "/cats/#{@cat.id}/edit") %> </li>
    </ul>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>